version: "3.7"

services:
  db:
    image: "postgres:14-alpine"
    ports:
      - "5434:5432"
    volumes:
      - dev_path_app_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  
volumes:
    dev_path_app_db:
