version: "3.7"

services:
  db:
    image: "postgres:14-alpine"
    ports:
      - "5434:5432"
    volumes:
      - dev_path_app_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
  mail:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  
volumes:
    dev_path_app_db:
