version: '3.7'

services:
  db:
    image: 'postgres:14-alpine'
    ports:
      - '5434:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'secret'
  mail:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
  redis:
    image: 'redis:5-alpine'
    command: 'redis-server'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  
volumes:
    db:
    redis:
